export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAYPAL_REQUEST = 'ORDER_PAYPAL_REQUEST'
export const ORDER_PAYPAL_SUCCESS = 'ORDER_PAYPAL_SUCCESS'
export const ORDER_PAYPAL_FAIL = 'ORDER_PAYPAL_FAIL'
export const ORDER_PAYPAL_RESET = 'ORDER_PAYPAL_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'

export const ORDER_TOGGLE_DELIVERED_REQUEST = 'ORDER_TOGGLE_DELIVERED_REQUEST'
export const ORDER_TOGGLE_DELIVERED_SUCCESS = 'ORDER_TOGGLE_DELIVERED_SUCCESS'
export const ORDER_TOGGLE_DELIVERED_FAIL = 'ORDER_TOGGLE_DELIVERED_FAIL'
