export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAYPAL_REQUEST = 'ORDER_PAYPAL_REQUEST'
export const ORDER_PAYPAL_SUCCESS = 'ORDER_PAYPAL_SUCCESS'
export const ORDER_PAYPAL_FAIL = 'ORDER_PAYPAL_FAIL'
export const ORDER_PAYPAL_RESET = 'ORDER_PAYPAL_RESET'
